spring:
  devtools:
    restart:
      enabled: ${DEVTOOLS_IS_DEV_MODE}
      additional-paths: src

line:
  bot:
    channel-token: ${LINE_BOT_CHANNEL_TOKEN}
    channel-secret: ${LINE_BOT_CHANNEL_SECRET}
    handler:
      path: /callback

oxford:
  base-url: ${OXFORD_BASE_URL}
  app-id: ${OXFORD_APP_ID}
  app-key: ${OXFORD_APP_KEY}
